INSERT INTO auth_permission (content_type_id, codename, name) VALUES (1, 'add_logentry', 'Can add log entry');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (1, 'change_logentry', 'Can change log entry');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (1, 'delete_logentry', 'Can delete log entry');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (2, 'add_user', 'Can add user');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (2, 'change_user', 'Can change user');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (2, 'delete_user', 'Can delete user');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (3, 'add_permission', 'Can add permission');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (3, 'change_permission', 'Can change permission');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (3, 'delete_permission', 'Can delete permission');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (4, 'add_group', 'Can add group');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (4, 'change_group', 'Can change group');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (4, 'delete_group', 'Can delete group');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (5, 'add_contenttype', 'Can add content type');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (5, 'change_contenttype', 'Can change content type');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (5, 'delete_contenttype', 'Can delete content type');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (6, 'add_session', 'Can add session');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (6, 'change_session', 'Can change session');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (6, 'delete_session', 'Can delete session');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (7, 'add_category', 'Can add category');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (7, 'change_category', 'Can change category');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (7, 'delete_category', 'Can delete category');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (8, 'add_tag', 'Can add tag');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (8, 'change_tag', 'Can change tag');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (8, 'delete_tag', 'Can delete tag');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (9, 'add_post', 'Can add post');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (9, 'change_post', 'Can change post');
INSERT INTO auth_permission (content_type_id, codename, name) VALUES (9, 'delete_post', 'Can delete post');